// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3aWTADoSLOxAzePQNdoeUx4aSNwkPWQk',
    appId: '1:953570842646:web:dbd6748c45b83c4ccafd37',
    messagingSenderId: '953570842646',
    projectId: 'sall-e-182b6',
    authDomain: 'sall-e-182b6.firebaseapp.com',
    storageBucket: 'sall-e-182b6.firebasestorage.app',
    measurementId: 'G-SXDLHQ3DRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCssXFZR4qleOi6K49vdHPWVZje4nODHUM',
    appId: '1:953570842646:android:ab4fe9c9150e17fdcafd37',
    messagingSenderId: '953570842646',
    projectId: 'sall-e-182b6',
    storageBucket: 'sall-e-182b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxOPF-do51U6SKhvxM_ToDK9jwuyNics',
    appId: '1:953570842646:ios:be2e9ff0690f5e93cafd37',
    messagingSenderId: '953570842646',
    projectId: 'sall-e-182b6',
    storageBucket: 'sall-e-182b6.firebasestorage.app',
    iosBundleId: 'com.example.sallEApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxOPF-do51U6SKhvxM_ToDK9jwuyNics',
    appId: '1:953570842646:ios:be2e9ff0690f5e93cafd37',
    messagingSenderId: '953570842646',
    projectId: 'sall-e-182b6',
    storageBucket: 'sall-e-182b6.firebasestorage.app',
    iosBundleId: 'com.example.sallEApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3aWTADoSLOxAzePQNdoeUx4aSNwkPWQk',
    appId: '1:953570842646:web:42b7acc5957e1814cafd37',
    messagingSenderId: '953570842646',
    projectId: 'sall-e-182b6',
    authDomain: 'sall-e-182b6.firebaseapp.com',
    storageBucket: 'sall-e-182b6.firebasestorage.app',
    measurementId: 'G-Q8GPMB0495',
  );
}
